apiVersion: v1
kind: Service
metadata:
  name: anomaly-detection-service
spec:
  selector:
    app: anomaly-detection
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer

