apiVersion: v1
kind: Service
metadata:
  name: signature-detection-service
spec:
  selector:
    app: signature-detection
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: LoadBalancer
