apiVersion: apps/v1
kind: Deployment
metadata:
  name: signature-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signature-detection
  template:
    metadata:
      labels:
        app: signature-detection
    spec:
      containers:
      - name: signature-detection
        image: sherlock1824/signature-detection:v3
        ports:
        - containerPort: 7000
