# traffic-capture-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traffic-capture-service
spec:
  selector:
    app: traffic-capture
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
